### ISSUE TITLE
ext:load data fails intermittently for JHipster app

### ISSUE THREAD

**Issue by Grant-Lay** [sabomichal/liquibase-mssql#11]
I am using this library as part of a JHipster app, following the instructions here:  https://jhipster.github.io/tips/004_tip_using_ms_sql_server.html

Occasionally when running the script on application startup for the first time in a new database I get the following error:

```
Caused by: liquibase.exception.MigrationFailedException: Migration failed for change set classpath:config/liquibase/changelog/00000000000000_initial_schema.xml::00000000000001::jhipster:
     Reason: liquibase.exception.DatabaseException: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert explicit value for identity column in table 'JHI_USER' when IDENTITY_INSERT is set to OFF.
```

Several attempts to re-run the app will eventually fix it without any modifications to the liquibase files.

**Comment by kSan** [comment]
Second that. Just spent few hours on this. It seems the `insertIdentityEnabled` has no effect in `loadData`.

**Comment by jlaacke** [comment]
That has been fixed with f0978e9 which will be part of the next release.

**Comment by sabomichal** [comment]
Released in 1.4.1

**Comment by Grant-Lay** [comment]
Confirming upgrading to version 1.4.1 fixes this.  Thanks!

**Comment by Grant-Lay** [comment]
This issue is occurring again when I upgraded the liquibase version from 3.3.2 to 3.4.1.   Workaround is to regress back to 3.3.2 and revert schema location to dbchangelog-3.3.xsd.

**Comment by jlaacke** [comment]
You have to use version 1.5 to be able to upgrade to liquibase 3.4.1

**Comment by romilbadhe** [comment]
This is not solved. I am using Jhipster Generator v6.4.1, still facing Reason: liquibase.exception.DatabaseException: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot insert explicit value for identity column in table 'JHI_USER' when IDENTITY_INSERT is set to OFF. Followed all the procedures mentioned https://www.jhipster.tech/tips/004_tip_using_ms_sql_server.html#how-to-use-jhipster-with-ms-sql-server

**Please suggest a workaround or solve this issue**

**Comment by jlaacke** [comment]
Are you explicitely using version 1.5 of liquibase-mssql (which differs from the version in JHipster documentation)?

**Comment by romilbadhe** [comment]
@jlaacke we are using the version which is provided in the pom.xml generated by Jhipster app..
is there anything i am missing
