### ISSUE TITLE
Support for setting index fill factors...

### ISSUE THREAD

**Issue by scrain** [sabomichal/liquibase-mssql#17]
First, I appreciate your effort is helping support this extension.  My company has a use case to have Liquibase control index fill factors.    We would be happy to help contribute a pull request if seemed like a valuable addition.

Thanks

**Comment by sabomichal** [comment]
Hi, I have to say I currently do not have any spare time to actively develop the plugin, however I am open to any pull requests and release a new version.

**Comment by scrain** [comment]
Thanks Michal.  I went ahead and added support for fillfactors to the create index and add-primary-key changes and they are working well for us in our projects.  I submitted a pull request with those changes for your review.

Thanks again,
Shawn

**Comment by scrain** [comment]
Hey Michal, thanks for accepting the pull request.  What would be the steps to get a new release published?  Is there something I could help with?  Thanks.

**Comment by sabomichal** [comment]
Hi,
I am planing to do it soon, I was having some trouble after upgrading my environment.
michal
