### ISSUE TITLE
The "liquibase-mssql.jar" file is missing at release v1.6.4

### ISSUE THREAD

**Issue by LazyLeecher** [sabomichal/liquibase-mssql#26]
Hi,

Where can I get the file "liquibase-mssql.jar"? It's not part of the zip file in releases v1.6.4, v1.6.3, etc

**Comment by sabomichal** [comment]
Well, you can find the jar in maven repository https://search.maven.org/artifact/com.github.sabomichal/liquibase-mssql/1.6.4/jar or build it yourself.
